kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: superlocust
networking:
  ipFamily: ipv4
  apiServerAddress: 127.0.0.1
nodes:
- role: control-plane
  #image: kindest/node:v1.21.1
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 7081
    protocol: TCP
  - containerPort: 443
    hostPort: 7443
    protocol: TCP