{{- if .Values.master.pdb.enabled }}
{{- if semverCompare "<1.21-0" $.Capabilities.KubeVersion.GitVersion }}
apiVersion: policy/v1beta1
{{- else }}
apiVersion: policy/v1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "locust.fullname" . }}-master
  labels:
    component: master
{{ include "locust.labels" . | indent 4 }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ template "locust.name" . }}
      component: "master"
{{- end }}
