apiVersion: v1
kind: Service
metadata:
  name: {{ template "locust.fullname" . }}
  labels:
{{ include "locust.labels" . | indent 4 }}
    component: "swarm"
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: swarm-p1
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: swarm
    {{- include "locust.selectorLabels" . | nindent 4 }}
