{{- if .Values.swarm.serviceAccount.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.swarm.serviceAccount.name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - services
  - endpoints
  verbs:
  - get
  - patch
  - watch
  - list
  - create
  - delete
  - update
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - patch
  - watch
  - list
  - create
  - delete
  - update
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - patch
  - watch
  - list
  - create
  - delete
  - update
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.swarm.serviceAccount.name }}
  labels:
{{ include "locust.labels" . | indent 4 }}
{{- with .Values.swarm.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.swarm.serviceAccount.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.swarm.serviceAccount.name }}
roleRef:
  kind: Role
  name: {{ .Values.swarm.serviceAccount.name }}
  apiGroup: ""

